name: agroflow
description: "AgroFlow - A smart assistant for farmers to manage crop tasks and markets."
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and icons
  cupertino_icons: ^1.0.6

  # Local data storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Notifications
  awesome_notifications: ^0.10.1
  timezone: ^0.9.2

  # Calendar & date support
  table_calendar: ^3.0.9
  intl: ^0.20.2

  # Utilities
  uuid: ^4.1.0
  shared_preferences: ^2.2.2

  # Image caching and picker
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7

  # Firebase services
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.17.2
  firebase_database: ^10.5.2
  firebase_storage: ^11.6.7

  # Networking and location
  http: ^1.2.1
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Hive code generation
  build_runner: ^2.4.8
  hive_generator: ^1.1.0

  # Launcher icon generation
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

false_secrets:
  - android/app/google-services.json

homepage: https://github.com/maritimkibet/agroflow
repository: https://github.com/maritimkibet/agroflow
