mutation CreateTask @auth(level: USER) {
  task_insert(data: {
    farmId: "123e4567-e89b-12d3-a456-426614174000",
    description: "Example Task",
    dueDate: "2024-12-31",
    status: "Open"
  })
}

query ListTasks @auth(level: USER) {
  tasks {
    id
    description
    dueDate
    status
  }
}

mutation UpdateTask($id: UUID!) @auth(level: USER) {
  task_update(key: {id: $id}, data: {
    status: "Completed"
  })
}

mutation DeleteTask($id: UUID!) @auth(level: USER) {
  task_delete(key: {id: $id})
}