name: Firebase Setup

on:
  workflow_call:
    inputs:
      flutter-version:
        required: false
        type: string
        default: '3.24.0'

jobs:
  setup-firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Create Firebase config files
      run: |
        # Create android/app/google-services.json (dummy for CI)
        mkdir -p android/app
        cat > android/app/google-services.json << 'EOF'
        {
          "project_info": {
            "project_number": "123456789",
            "project_id": "agroflow-test",
            "storage_bucket": "agroflow-test.appspot.com"
          },
          "client": [
            {
              "client_info": {
                "mobilesdk_app_id": "1:123456789:android:abcdef123456",
                "android_client_info": {
                  "package_name": "com.example.agroflow"
                }
              },
              "oauth_client": [
                {
                  "client_id": "123456789-abcdef.apps.googleusercontent.com",
                  "client_type": 3
                }
              ],
              "api_key": [
                {
                  "current_key": "AIzaSyDummyKeyForCI"
                }
              ],
              "services": {
                "appinvite_service": {
                  "other_platform_oauth_client": [
                    {
                      "client_id": "123456789-abcdef.apps.googleusercontent.com",
                      "client_type": 3
                    }
                  ]
                }
              }
            }
          ],
          "configuration_version": "1"
        }
        EOF
        
        # Create ios/Runner/GoogleService-Info.plist (dummy for CI)
        mkdir -p ios/Runner
        cat > ios/Runner/GoogleService-Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>CLIENT_ID</key>
          <string>123456789-abcdef.apps.googleusercontent.com</string>
          <key>REVERSED_CLIENT_ID</key>
          <string>com.googleusercontent.apps.123456789-abcdef</string>
          <key>API_KEY</key>
          <string>AIzaSyDummyKeyForCI</string>
          <key>GCM_SENDER_ID</key>
          <string>123456789</string>
          <key>PLIST_VERSION</key>
          <string>1</string>
          <key>BUNDLE_ID</key>
          <string>com.example.agroflow</string>
          <key>PROJECT_ID</key>
          <string>agroflow-test</string>
          <key>STORAGE_BUCKET</key>
          <string>agroflow-test.appspot.com</string>
          <key>IS_ADS_ENABLED</key>
          <false></false>
          <key>IS_ANALYTICS_ENABLED</key>
          <false></false>
          <key>IS_APPINVITE_ENABLED</key>
          <true></true>
          <key>IS_GCM_ENABLED</key>
          <true></true>
          <key>IS_SIGNIN_ENABLED</key>
          <true></true>
          <key>GOOGLE_APP_ID</key>
          <string>1:123456789:ios:abcdef123456</string>
        </dict>
        </plist>
        EOF