name: Build and Release APK

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.1

jobs:
  build-and-release:
    name: Build and Release APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Firebase config files (for CI)
      run: |
        # Create dummy Firebase config files for CI builds
        mkdir -p android/app
        echo '{"project_info":{"project_id":"agroflow-ci"},"client":[{"client_info":{"android_client_info":{"package_name":"com.example.agroflow"}},"api_key":[{"current_key":"dummy"}],"services":{"appinvite_service":{}}}]}' > android/app/google-services.json
        
        mkdir -p ios/Runner
        echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>PROJECT_ID</key><string>agroflow-ci</string><key>BUNDLE_ID</key><string>com.example.agroflow</string><key>API_KEY</key><string>dummy</string></dict></plist>' > ios/Runner/GoogleService-Info.plist
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Verify Flutter installation
      run: flutter doctor -v
      
    - name: Generate code (Hive adapters)
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
    - name: Build APK
      run: flutter build apk --release --verbose
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: AgroFlow ${{ steps.get_version.outputs.VERSION }}
        body: |
          🌱 **AgroFlow ${{ steps.get_version.outputs.VERSION }}**
          
          ## ✨ What's New
          - Enhanced messaging system with real-time chat
          - Improved AI assistant with local responses
          - Better offline functionality
          - GitHub Releases integration for updates
          
          ## 🐛 Bug Fixes
          - Fixed authentication flow issues
          - Improved marketplace loading performance
          - Better error handling in messaging
          - Fixed calendar synchronization
          
          ## 📱 Installation
          1. Download the APK file below
          2. Enable "Install from unknown sources" in Android settings
          3. Install the APK file
          
          ## 🔄 Upgrade Notes
          - This version is compatible with all previous versions
          - Your data will be preserved during upgrade
          
          **Full Changelog**: https://github.com/${{ github.repository }}/compare/v1.0.0...${{ steps.get_version.outputs.VERSION }}
        files: |
          build/app/outputs/flutter-apk/app-release.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}